[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=/Brepro"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-arg=/Brepro"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-reproducible", "-C", "link-arg=-Wl,-no_adhoc_codesign"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-Wl,-reproducible", "-C", "link-arg=-Wl,-no_adhoc_codesign"]
